RESTORE DATABASE [DATABASE NAME] FROM DISK = 'PATH TO .bak FILE'
WITH FILE = 1,
MOVE '[NAME OF DATABASE FILE]' TO 'var/opt/mssql/data/[YOUR.MDF FILE]',
MOVE '[NAME OF YOUR LOG FILE]' TO 'var/opt/mssql/data/[YOUR.LDF FILE]'
GO